### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by azuk132435** [cse110-sp24-group31/warmup-exercise#17]
**Description of Feature wanted**
Add an icon for the site on the browser.

**Describe how we would implement this solution**
Code it into the html file to display on the website from an image online.

**Additional comments**
N/A

**Comment by NewtonLC** [comment]
Can we use our team logo as the icon???

**Comment by azuk132435** [comment]
I don't think so. I think a list fits better too. You would need to shrink our logo super small yet have its content still visable when I dont think is possible.
